"""adicionando usuario_id em categorias

Revision ID: 8900a40cba06
Revises: 080cf212b95d
Create Date: 2026-05-25 20:12:25.420442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8900a40cba06'
down_revision = '080cf212b95d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        # batch_op.create_foreign_key(None, 'usuarios', ['usuario_id'], ['id'])
        pass

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
